Disable 'unused parameter' warning
Fixes tons of warnings turned into errors on Fedora 20:

  [exec] /home/penberg/jffi/jni/jffi/FastLongInvoke.c: In function ‘Java_com_kenai_jffi_Foreign_invokeL0’:
  [exec] /home/penberg/jffi/jni/jffi/FastLongInvoke.c:64:46: error: unused parameter ‘env’ [-Werror=unused-parameter]
  [exec]  Java_com_kenai_jffi_Foreign_invokeL0(JNIEnv* env, jobject self, jlong ctxAddress, jlong function)
  [exec]                                               ^

Signed-off-by: Pekka Enberg <penberg@iki.fi>